### ISSUE TITLE
linter failing in amp

### ISSUE THREAD

**Issue by gitpaulsmith** [alphamatic/amp#1744]
After I did a `docker_pull`, the linter stopped working for me in `amp`:
```
> i lint -b
INFO: > cmd='/Users/paul/src/venv/amp.client_venv/bin/invoke lint -b'
>>ENV<<: is_inside_container=False: code_version=amp-1.1.1, container_version=None, is_inside_docker=False, is_inside_ci=False, CI_defined=False, CI='nan'
>>ENV<<: AM_AWS_PROFILE=True AM_ECR_BASE_PATH=True AM_S3_BUCKET=True AM_TELEGRAM_TOKEN=True AWS_ACCESS_KEY_ID=False AWS_DEFAULT_REGION=False AWS_SECRET_ACCESS_KEY=False GH_ACTION_ACCESS_TOKEN=False
## lint: 
rm linter_output.txt
09-23_21:15 INFO  lib_tasks           : lint                          : 2573: Files to lint:
core/dataflow_model/model_evaluator.py
core/dataflow_model/utils.py
(docker run --rm -t -v '/Users/paul/src/lemonade1':/src --workdir=/src/amp 665840871993.dkr.ecr.us-east-1.amazonaws.com/dev_tools:prod 'pre-commit run -c /app/.pre-commit-config.yaml --files core/dataflow_model/model_evaluator.py core/dataflow_model/utils.py') 2>&1 | tee -a linter_output.txt
##> devops/docker_build/entrypoint.sh
# Activate environment 'venv'
##> devops/docker_build/entrypoint/aws_credentials.sh
Can't find /root/.aws: exiting
Assigning AWS_DEFAULT_REGION='us-east-1'
##> devops/docker_build/entrypoint/patch_environment_variables.sh
# Set PATH
amp dir '/src/amp/amp' doesn' exist
09-23_21:15 INFO  lib_tasks           : lint                          : 2603: Parsing 'linter_output.txt'
09-23_21:15 INFO  lib_tasks           : lint                          : 2608: Saved cfile in './linter_warnings.txt'
```

**Comment by gpsaggese** [comment]
Fixed. Can you pls do `i docker pull` and confirm that it works?

**Comment by gitpaulsmith** [comment]
It works in the sense that it runs. The behavior seems different, though, with tons of false positives, and I'm not sure what's to be expected and what's not.

**Comment by gpsaggese** [comment]
Can you post command and output?

**Comment by gitpaulsmith** [comment]
There's a litany of things. We can discuss when we sync.

**Comment by gitpaulsmith** [comment]
The tail of this log shows the chatting mypy failures. Because there are so many, the legitimate issues are hard to spot:
``core/dataflow_model/model_evaluator.py:404:[amp_pylint] [E1101(no-member), ModelEvaluator.from_result_bundle_dict] Module 'helpers.dbg' has 
no 'get_memory_usage_as_str' member 
core/dataflow_model/model_evaluator.py:418:[amp_pylint] [W0703(broad-except), ModelEvaluator.from_result_bundle_dict] Catching too general e
xception Exception
core/dataflow_model/model_evaluator.py:419:[amp_pylint] [W1201(logging-not-lazy), ModelEvaluator.from_result_bundle_dict] Use lazy % formatt
ing in logging functions
core/dataflow_model/model_evaluator.py:423:[amp_pylint] [R1720(no-else-raise), ModelEvaluator.from_result_bundle_dict] Unnecessary "else" af
ter "raise"
core/dataflow_model/model_evaluator.py:436:[amp_pylint] [E1101(no-member), ModelEvaluator.from_result_bundle_dict] Module 'helpers.dbg' has 
no 'get_memory_usage_as_str' member 
core/dataflow_model/model_evaluator.py:456:[amp_pylint] [E1101(no-member), ModelEvaluator.from_eval_config] Module 'core.dataflow_model.util
s' has no 'load_experiment_artifacts' member; maybe '_load_experiment_artifacts'?
core/dataflow_model/model_evaluator.py:547:[amp_pylint] [E1101(no-member), ModelEvaluator.aggregate_models] Module 'helpers.dbg' has no 'get
_memory_usage_as_str' member
core/dataflow_model/model_evaluator.py:605:[amp_pylint] [E1101(no-member), ModelEvaluator.calculate_stats] Module 'helpers.dbg' has no 'get_
memory_usage_as_str' member
core/dataflow_model/model_evaluator.py:689:[amp_pylint] [E1101(no-member), ModelEvaluator.compute_pnl] Module 'helpers.dbg' has no 'get_memo
ry_usage_as_str' member
core/dataflow_model/notebooks/Master_incremental_single_name_model_evaluator.py:25:[amp_pylint] [E0611(no-name-in-module), ] No name 'increm
ental_single_name_model_evaluator' in module 'core.dataflow_model'
core/dataflow_model/notebooks/Master_incremental_single_name_model_evaluator.py:27:[amp_pylint] [R0402(consider-using-from-import), ] Use 'f
rom helpers import dbg' instead
core/dataflow_model/notebooks/Master_incremental_single_name_model_evaluator.py:45:[amp_pylint] [E1101(no-member), ] Class 'Config' has no '
from_env_var' member
core/dataflow_model/utils.py:326:[amp_pylint] [E1101(no-member), _get_experiment_subdirs] Module 'helpers.s3' has no 'expand_archived_data' 
member
core/dataflow_model/utils.py:387:[amp_pylint] [E1101(no-member), _load_experiment_artifact] Class 'ResultBundle' has no 'from_pickle' member
core/dataflow_model/utils.py:392:[amp_pylint] [E1101(no-member), _load_experiment_artifact] Class 'ResultBundle' has no 'from_pickle' member
core/dataflow_model/utils.py:402:[amp_pylint] [W1514(unspecified-encoding), _load_experiment_artifact] Using open without explicitly specify
ing an encoding
core/dataflow_model/utils.py:485:[amp_pylint] [E1101(no-member), _yield_rolling_experiment_out_of_sample_df] Module 'helpers.dbg' has no 'da
ssert_strictly_increasing_index' member
core/dataflow_model/utils.py:523:[amp_pylint] [E1101(no-member), load_experiment_artifacts] Module 'helpers.dbg' has no 'get_memory_usage_as
_str' member
core/dataflow_model/utils.py:528:[amp_mypy] error: Incompatible types in assignment (expression has type "Callable[[Arg(str, 'src_dir'), Arg
(str, 'file_name_prefix'), Arg(Dict[str, Any], 'load_rb_kwargs'), DefaultArg(Optional[Iterable[int]], 'selected_idxs'), DefaultArg(Optional[
str], 'aws_profile')], Iterable[Tuple[str, Any]]]", variable has type "Callable[[Arg(str, 'src_dir'), Arg(str, 'file_name'), Arg(Dict[str, A
ny], 'load_rb_kwargs'), DefaultArg(Optional[Iterable[int]], 'selected_idxs'), DefaultArg(Optional[str], 'aws_profile')], Iterable[Tuple[str,
 Any]]]")  [assignment]
core/dataflow_model/utils.py:530:[amp_pylint] [W0715(raising-format-tuple), load_experiment_artifacts] Exception arguments suggest string fo
rmatting might be intended
core/dataflow_model/utils.py:531:[amp_pylint] [W0622(redefined-builtin), load_experiment_artifacts] Redefining built-in 'iter'
core/dataflow_model/utils.py:534:[amp_mypy] error: Argument "load_rb_kwargs" has incompatible type "Optional[Dict[str, Any]]"; expected "Dic
t[str, Any]"  [arg-type]
core/dataflow_model/utils.py:543:[amp_pylint] [E1101(no-member), load_experiment_artifacts] Module 'helpers.dbg' has no 'get_memory_usage_as
_str' member
core/dataflow_model/utils.py:549:[amp_pylint] [E1101(no-member), load_experiment_artifacts] Module 'helpers.dbg' has no 'get_memory_usage_as
_str' member
`

``

**Comment by gitpaulsmith** [comment]
Also, the linter thinks this is a reasonable import name:
```
import core.dataflow_model.incremental_single_name_model_evaluator as cdtfmoinsinamodeva
```

**Comment by gpsaggese** [comment]
Fixed
